---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: lbpools.sncs-uk.io
spec:
  group: sncs-uk.io
  scope: Cluster
  names:
    plural: lbpools
    singular: lbpool
    kind: LoadBalancerPool
  versions:
  - name: v1beta1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        description: >-
          A pool representing available IP addresses to use for Load Balancer public addresses
        type: object
        properties:
          apiVersion:
            description: >-
              APIVersion defines the versioned schema of this representation of
              an object.

              Servers should convert recognized schemas to the latest internal
              value, and

              may reject unrecognized values.

              More info:
              https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: >-
              Kind is a string value representing the REST resource this object
              represents.

              Servers may infer this from the endpoint the client submits
              requests to.

              Cannot be updated.

              In CamelCase.

              More info:
              https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: >-
              Specification of the desired state of the Certificate resource.

              https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status
            type: object
            properties:
              ipv4:
                description: IPv4 CIDR from which to assign addresses
                type: string
              ipv6:
                description: IPv6 CIDR from which to assign addresses
                type: string
              excludev4:
                description: list of ipv4 addresses to exclude from the range
                type: array
                items:
                  type: string
              excludev6:
                description: list of ipv6 addresses to exclude from the range
                type: array
                items:
                  type: string
                
                
    additionalPrinterColumns:
    - jsonPath: .spec.ipv4
      name: ipv4
      type: string
      description: The IPv4 CIDR from which to assign addresses
    - jsonPath: .spec.ipv6
      name: ipv6
      type: string
      description: The IPv6 CIDR from which to assign addresses