---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-reader
  labels:
    {{- include "fortigate-lb-controller.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  - "apps"
  resources:
  - "pods"
  - "replicasets"
  verbs:
  - "get"
  - "list"
- apiGroups:
  - "apps"
  resources:
  - "deployments"
  verbs:
  - "get"
  - "list"
  - "update"
  - "patch"