apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fortigate-lb-controller.secretName" .}}
data:
  FORTIOS_ACCESS_TOKEN: {{ .Values.controller.fortigate.token | b64enc }}
  FORTIOS_ACCESS_USERNAME: {{ .Values.controller.fortigate.username | b64enc }}
  FORTIOS_ACCESS_PASSWORD: {{ .Values.controller.fortigate.password | b64enc }}
type: Opaque